services:
  the-perfect-boilerplate-backend:
    image: ghcr.io/evedes/the-perfect-boilerplate/backend:latest
    container_name: the-perfect-boilerplate-backend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      API_PORT: ${API_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL:-true}
    networks:
      - the-perfect-boilerplate

  the-perfect-boilerplate-frontend:
    container_name: the-perfect-boilerplate-frontend
    image: ghcr.io/evedes/the-perfect-boilerplate/frontend:latest
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      API_URL: ${API_URL}
    depends_on:
      - the-perfect-boilerplate-backend
    networks:
      - the-perfect-boilerplate

networks:
  the-perfect-boilerplate:
