services:
  the-perfect-boilerplate-backend:
    container_name: the-perfect-boilerplate-backend
    image: ghcr.io/evedes/the-perfect-boilerplate/backend:latest
    restart: unless-stopped
    env_file:
      - .env.the-perfect-boilerplate
  the-perfect-boilerplate-frontend:
    container_name: the-perfect-boilerplate-frontend
    image: ghcr.io/evedes/the-perfect-boilerplate/frontend:latest
    restart: unless-stopped
    env_file:
      - .env.the-perfect-boilerplate
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    depends_on:
      - the-perfect-boilerplate-backend

networks:
    the-perfect-boilerplate:
